create Database Oscars; 

create table Movie(
Title VARCHAR(50) PRIMARY KEY NOT NULL,
ReleaseDate DATE PRIMARY KEY NOT NULL, 
Language VARCHAR(20) NOT NULL, 
Country VARCHAR(50) NOT NULL, 
Runtime INT  NOT NULL
);

create table MovieProductionCom(
Title VARCHAR(50) PRIMARY KEY NOT NULL,
ReleaseDate DATE PRIMARY KEY NOT NULL, 
ProductionCompany VARCHAR(50) PRIMARY KEY NOT NULL,
FOREIGN KEY (Title) REFERENCES Movie(Title) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ReleaseDate) REFERENCES Movie(ReleaseDate) ON DELETE CASCADE ON UPDATE CASCADE
);
create table Person(
FName VARCHAR(50) PRIMARY KEY NOT NULL, 
MName VARCHAR(50) PRIMARY KEY NOT NULL,
LName VARCHAR(50) PRIMARY KEY NOT NULL,
DeathDate DATE , 
BIRTHDATE DATE NOT NULL, 
CountryOfBirth VARCHAR(20) NOT NULL 
);

create table WorksAt(
FName VARCHAR(50) PRIMARY KEY NOT NULL, 
MName VARCHAR(50) PRIMARY KEY NOT NULL,
LName VARCHAR(50) PRIMARY KEY NOT NULL,
Title VARCHAR(50) PRIMARY KEY NOT NULL,
ReleaseDate DATE PRIMARY KEY NOT NULL, 
Role VARCHAR(50) NOT NULL,
FOREIGN KEY (FName) REFERENCES Person(FName) ON DELETE CASCADE ON UPDATE CASCADE,  
FOREIGN KEY (MName) REFERENCES Person(MName) ON DELETE CASCADE ON UPDATE CASCADE,  
FOREIGN KEY (LName) REFERENCES Person(LName) ON DELETE CASCADE ON UPDATE CASCADE,  
FOREIGN KEY (Title) REFERENCES Movie(Title) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ReleaseDate) REFERENCES Movie(ReleaseDate) ON DELETE CASCADE ON UPDATE CASCADE
);

create table AcademyAwards(
IteratioNo INT PRIMARY KEY NOT NULL,  
Year INT PRIMARY KEY NOT NULL, 
Site VARCHAR(50)
);
create table AcademyAwardsHost(
IteratioNo INT PRIMARY KEY NOT NULL,  
Year INT PRIMARY KEY NOT NULL,
Host VARCHAR(50) PRIMARY KEY NOT NULL, 
FOREIGN KEY (IteratioNo) REFERENCES AcademyAwards(IteratioNo) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Year) REFERENCES AcademyAwards(Year) ON DELETE CASCADE ON UPDATE CASCADE
);    


create Table Nomination(
Title VARCHAR(50) PRIMARY KEY NOT NULL,
ReleaseDate DATE PRIMARY KEY NOT NULL, 
IteratioNo INT PRIMARY KEY NOT NULL,  
Year INT PRIMARY KEY NOT NULL, 
Category VARCHAR(50) PRIMARY KEY NOT NULL, 
IsGranted boolean NOT NULL, 
FOREIGN KEY (Title) REFERENCES Movie(Title) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ReleaseDate) REFERENCES Movie(ReleaseDate) ON DELETE CASCADE ON UPDATE CASCADE, 
FOREIGN KEY (IteratioNo) REFERENCES AcademyAwards(IteratioNo) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Year) REFERENCES AcademyAwards(Year) ON DELETE CASCADE ON UPDATE CASCADE
); 

create table User(
EmailAddress VARCHAR(50) PRIMARY KEY NOT NULL, 
Username VARCHAR(50) NOT NULL, 
Age INT NOT NULL, 
Gender CHAR(10) NOT NULL, 
Birthdate DATE NOT NULL, 
Country VARCHAR(20) NOT NULL
);

create table UserNomination(
EmailAddress VARCHAR(50) PRIMARY KEY NOT NULL, 
Category VARCHAR(50) PRIMARY KEY NOT NULL, 
Title VARCHAR(50) PRIMARY KEY NOT NULL,
ReleaseDate DATE PRIMARY KEY NOT NULL, 
IteratioNo INT PRIMARY KEY NOT NULL,  
Year INT PRIMARY KEY NOT NULL,
FName VARCHAR(50) , 
MName VARCHAR(50) ,
LName VARCHAR(50) ,
FOREIGN KEY (Title) REFERENCES Movie(Title) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ReleaseDate) REFERENCES Movie(ReleaseDate) ON DELETE CASCADE ON UPDATE CASCADE, 
FOREIGN KEY (IteratioNo) REFERENCES AcademyAwards(IteratioNo) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Year) REFERENCES AcademyAwards(Year) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (EmailAddress) REFERENCES User(EmailAddress) ON DELETE CASCADE ON UPDATE CASCADE
);


